### ISSUE TITLE
Error! I put the fingerprint, coordinates etc. But it doesn't works 

### ISSUE THREAD

**Issue by zzz1337-sys** [possatti/pixelbot#1]
That's happens with me, I put right the things and it doesn't works
![screenshot_3](https://user-images.githubusercontent.com/29678843/27512197-0077d142-590f-11e7-9d15-6899ba5e7c42.png)

![screenshot_1](https://user-images.githubusercontent.com/29678843/27512184-a8040314-590e-11e7-89d7-15bc5a79f70c.png)

**Comment by zzz1337-sys** [comment]
I think u speak portuguese, so it's better to me if you talk in portuguese, if u want.

**Comment by possatti** [comment]
Yes, I do speak Portuguese (:D). Eu estou muito surpreso que já tenha gente usando esse código! Eu mandei o código ainda hoje para o Github! Hahaha

De qualquer forma. Tente colocar os argumentos como um array para a função `parse_args`, ao invés de colocar no `help`. Desse jeito:

```python
if __name__ == '__main__':
	parser = argparse.ArgumentParser(description='')
	parser.add_argument('file_path', help='The file indicating what should be built by the robot. It can be an image or a text file.')
	parser.add_argument('x_offset', type=int, help='X coordinate for where in the canvas the drawing should be painted.')
	parser.add_argument('y_offset', type=int, help='Y coordinate for where in the canvas the drawing should be painted.')
	parser.add_argument('fingerprint', help='Your fingerprint.')
	parser.add_argument('-t', '--bot-template', default='template/pixelbot-template.js', help='Location do the template which will produce the bot.')
	parser.add_argument('-s', '--save-to', help='Where the bot script should be saved to. Defaults to <file_path> terminating with `.js`.')
	######  Aqui:  ######
	args = parser.parse_args(['pixelbot-master/pixelbot.txt', '-4509', '1426', '2b797aaab73325529316fac08a02afb6.'])
	main()
```

Verifica se eu digitei o seu fingerprint certinho. E eu acredito que o arquivo de texto que você está tentando usar deve ser `examples/pixelbot.txt` ao invés de `pixelbot-master/pixelbot.txt`.

Se tiver mais dúvidas, é só perguntar. :)

**Comment by possatti** [comment]
E tenha em mente que eu ainda estou tendo muitos erros com esse negócio. Ele funcionou comigo há poucos dias atrás. Mas eu estou tentando hoje e não paro de receber o erro `{"errors":[{"msg":"You are using a proxy!!!11!"}]}`. Ainda não sei como resolver isso.

**Comment by zzz1337-sys** [comment]
Eu alterei o destino do pixelbot.txt, por isso q ali estava diferente do destino original.

**Comment by zzz1337-sys** [comment]
Prossegue o mesmo erro! 
![screenshot_1](https://user-images.githubusercontent.com/29678843/27512558-ba7bd61e-591a-11e7-94c6-c35ae372239d.png)

**Comment by zzz1337-sys** [comment]
@possatti O lance do You Are a Proxy, ocorre quando seu ping tá mt alto, ou deve ser algo relacionado ao código mesmo

**Comment by possatti** [comment]
Hmmm. O erro dessa vez é diferente, então tá quase lá. Deve ser porque a barra é invertida no Windows, aí ele não está encontrando o arquivo. Eu uso Linux na maior parte do tempo, e nós usamos essa barra: `/`. Mas no windows você precisa usar contra-barra: `\`.

Se ainda assim não funcionar, tenta usar o caminho completo: `C:\Users\pc\Desktop\pixelbot-master\botfactory.py`.

**Comment by possatti** [comment]
Se você tiver um erro `No such file or directory: 'template/pixelbot-template.js'` é pq o script não está encontrando o template. Mas aí é só você mostrar pra ele onde está o template. Assim:

```python
args = parser.parse_args(['pixelbot-master/pixelbot.txt', '-4509', '1426', '2b797aaab73325529316fac08a02afb6', '--bot-template', 'C:\Users\pc\Desktop\pixelbot-master\template\pixelbot-template.js'])
```

**Comment by zzz1337-sys** [comment]
Ok! Vou testar.

**Comment by zzz1337-sys** [comment]
if __name__ == '__main__':
	parser = argparse.ArgumentParser(description='')
	parser.add_argument('file_path', help='The file indicating what should be built by the robot. It can be an image or a text file.')
	parser.add_argument('x_offset', type=int, help='X coordinate for where in the canvas the drawing should be painted.')
	parser.add_argument('y_offset', type=int, help='Y coordinate for where in the canvas the drawing should be painted.')
	parser.add_argument('fingerprint', help='Your fingerprint.')
	parser.add_argument('-t', '--bot-template', default='template\pixelbot-template.js', help='Location do the template which will produce the bot.')
	parser.add_argument('-s', '--save-to', help='Where the bot script should be saved to. Defaults to <file_path> terminating with `.js`.')
	######  Aqui:  ######
	args = parser.parse_args(['pixelbot-master\pixelbot.txt', '-4509', '1426', '2b797aaab73325529316fac08a02afb6', '--bot-template', 'C:\Users\pc\Desktop\pixelbot-master\template\pixelbot-template.js'])
	main()

======
Não reconheceu mesmo assim! Devo estar ocupando seu tempo hdsfhasdh. Perdão por isso

![screenshot_3](https://user-images.githubusercontent.com/29678843/27512758-8f58b54e-5922-11e7-895b-46af890d0b32.png)

**Comment by possatti** [comment]
Hmm. Aparentemente você tem que duplicar as contra-barras também (https://stackoverflow.com/a/1347854). Me esqueci desse detalhe.

Tente:

```python
args = parser.parse_args(['pixelbot-master\\pixelbot.txt', '-4509', '1426', '2b797aaab73325529316fac08a02afb6', '--bot-template', 'C:\\Users\\pc\\Desktop\\pixelbot-master\\template\\pixelbot-template.js'])
```

**Comment by possatti** [comment]
E quanto a perder tempo, na verdade eu estou feliz que tem alguém para usar esse projeto. Kkkkk

Posso perguntar como você encontrou esse projeto? Eu criei ele ao longo da semana, mas só coloquei ele na internet hoje. Como você encontrou?

**Comment by zzz1337-sys** [comment]
Eu estava dando uma pesquisada sobre bots para pixel canvas, pra dar uma estudada no código. Ai achei esse teu :)

**Comment by zzz1337-sys** [comment]
Conseguindo fluir com o código?

**Comment by possatti** [comment]
Bastante :D ! Agora eu estou fazendo as chamadas usando a mesma função que o pixelcanvas usa (`fetch()` ao invés de `xhr`). Dessa forma, tudo voltou a funcionar novamente. Eu consegui pintar a paleta de cores inteira e de uma vez só:

![image](https://user-images.githubusercontent.com/5595012/27521552-b6b69606-59f4-11e7-9033-498816685f4a.png)

Porém eu fui tentar pintar algo maior (`examples/space_invaders.png`), e minha internet caiu logo nos primeiros pixels. Mesmo eu podendo continuar pintando de onde estava (desde que eu não feche a janela), eu sei que é preciso uma forma do script detectar quais pixels já estão pintados, e pintar apenas os restantes.

Isso vai dar algum trabalho, e eu não sei quando vou ter tempo de novo pra trabalhar com isso. Mas, por enquanto, parece que está tudo funcionando normal agora. :D

**Comment by zzz1337-sys** [comment]
Opa! É bom ver brasileiros entendendo tanto de programação, por enquanto não sei nada rsrsrs.
Teu bot está ficando excelente, espero conseguir usar quando estiver pronto!

**Comment by possatti** [comment]
Obrigado, cara! Eu espero conseguir fazer isso ficar legal.

**Comment by zzz1337-sys** [comment]
![screenshot_2](https://user-images.githubusercontent.com/29678843/27751734-1ae967f8-5db4-11e7-8b7a-7d736835e3da.png)

Código q estou usando

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('file_path', help='botafogo.png')
    parser.add_argument('x_offset', type=int, help='-864')
    parser.add_argument('y_offset', type=int, help='-193')
    parser.add_argument('fingerprint', help='6e12494c6084705bc93ebc780879d15c')
    parser.add_argument('-t', '--bot-template', default='template/pixelbot-fetch-template.js', help='template/pixelbot-fetch-template.js')
    parser.add_argument('-s', '--save-to', help='botafogo.js')
	args = parser.parse_args(['botafogo.png', '-864', '-193', '6e12494c6084705bc93ebc780879d15c', '--bot-template', 'C://Users/pc/Desktop/pixelbot-master/template/pixelbot-template.js'])
    main()
