### ISSUE TITLE
CONSEEEEEGUI!!!!!!!!

### ISSUE THREAD

**Issue by zzz1337-sys** [possatti/pixelbot#3]
DPS DE TANTA LUTA, ACHEI A SOLUÇÃO :))))

**Comment by possatti** [comment]
kkkkk. Que bom. O problema era a indentação do código (tabs e espaços)?

**Comment by zzz1337-sys** [comment]
Não kkk. Consegui pelo cmd python botfactory.py teste.png -473 -162
fea10a5f4fe57f5f7b442e8d528c07e9

**Comment by ZeedyPixel** [comment]
Eu n tava rodando o arquivo pelo cmd, e tava editando o código. :////

**Comment by zzz1337-sys** [comment]
![screenshot_6](https://user-images.githubusercontent.com/29678843/27764954-fdaff12a-5e7b-11e7-99b6-82ff3842e734.png)

Fiz esse hud! (79 = Quantidade de pixeis colocados) Achei q ficou bem bacana, o problema é q tentei fazer pra ele detectar os pixeis já pintados e passar para o próximo, e pintar em random pra mais de 1 pessoa conseguir usar, para os 2 n colocarem os pixeis no mesmo lugar.

**Comment by possatti** [comment]
Poxa, que maneiro! Sério mesmo. Gostei da ideia de colocar informações nessa bolha. Muito útil. Eu tenho vontade de fazer duas das coisas que você falou. O script precisa exibir o progresso de uma forma mais intuitiva, falando quantos pixels faltam, e quanto tempo falta para pintar o próximo pixel. E também ficar mais fácil de colaborar com outra pessoa.

Pessoalmente eu acho que a melhor forma de implementar essa ideia de colaboração. É se o script conseguisse detectar quais pixels já foram pintados, e então pintar apenas os que faltam. Antes de pintar cada pixel, ele verifica se ele já foi pintado. Isso junto com a ideia do aleatório realmente tornaria bem fácil de mais de uma pessoa pintar a mesma figura.

Eu comecei a experimentar essa ideia de detectar quais pixels estão pintados. Mas pra isso é necessário decodificar esse tal de "bigchunk". Eu fiz uma tentativa (tá dentro da pasta `drafts`), mas tem alguma coisa que eu não entendi ainda.

Eu pretendo continuar com isso, mas nas próximas semanas eu vou estar bem ocupado com alguns trabalhos do mestrado. Mas quando eu tiver mais algum tempo, eu vou voltar nisso.

**Comment by zzz1337-sys** [comment]
Certo! Boa sorte no mestrado.

**Comment by mcloviinx** [comment]
Eae pessoal, boa noite... Tem como explicar passo a passo? :D Ajudinha básica

**Comment by mcloviinx** [comment]
C:\Users\McLovin>C:\Users\McLovin\Desktop\pixelbot-master\botfactory.py D:\pixel
.png 644 222 asfafsa4
Parsing file...
Producing bot from image 'D:\pixel.png' with resolution 150x150.
Number of points produced: 12708.
Saving bot to 'D:\pixel.js'...
Traceback (most recent call last):
  File "C:\Users\McLovin\Desktop\pixelbot-master\botfactory.py", line 141, in <m
odule>
    main()
  File "C:\Users\McLovin\Desktop\pixelbot-master\botfactory.py", line 129, in ma
in
    produce_bot(points, args.x_offset, args.y_offset, args.fingerprint, bot_save
_path)
  File "C:\Users\McLovin\Desktop\pixelbot-master\botfactory.py", line 92, in pro
duce_bot
    with open(args.bot_template) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'template/pixelbot-fetch
-template.js'

**Comment by mcloviinx** [comment]
O que eu faço?

**Comment by possatti** [comment]
Você quase conseguiu, mas ele não está encontrando o arquivo de template, pq não você está na raíz do projeto. Mas você pode mostrar pra ele onde está o arquivo do template usando a opção `--bot-template` ou `-t`.

Se você executasse o seguinte, eu acredito que funcionaria:

```
C:\Users\McLovin\Desktop\pixelbot-master\botfactory.py D:\pixel.png 644 222 asfafsa4 -t C:\Users\McLovin\Desktop\pixelbot-master\template\pixelbot-fetch-template.js
```

Aí ele vai criar o script em `D:\pixel.js`. Aí você copia o conteúdo e cola no Console do seu navegador. E espera ele terminar de pintar. A sua imagem é bem grande, então vai demorar um booooom tempo :) . Sugiro você experimentar uma imagem menor primeiro, no máximo 10x10. Além disso você precisa colocar o seu fingerprint também. Se não o pixelcanvas não vai aceitar as requisições.

**Comment by mcloviinx** [comment]
Funcionou!!! OBRIGADO

C:\Users\McLovin>C:\Users\McLovin\Desktop\pixelbot-master\botfactory.py D:\pixel
l.png 5571 1178 28977e26f78f82624a1cd92a04b55a31 -t C:\Users\McLovin\Desktop\pix
elbot-master\template\pixelbot-fetch-template.js
Parsing file...
Producing bot from image 'D:\pixell.png' with resolution 10x10.
Number of points produced: 50.
Saving bot to 'D:\pixell.js'...
Using template from `C:\Users\McLovin\Desktop\pixelbot-master\template\pixelbot-
fetch-template.js`.
All done.
################
Agora iriei executar no console...

**Comment by itsfolf** [comment]
Aqui ta dando tuple index out of range na linha 73 e n to conseguindo resolver

EDIT: Seria bom se atualizasse pro novo pixelcanvas (basta adicionar a cordenada z que é a soma de y e x)

**Comment by possatti** [comment]
Se você puder mandar o log do erro, fica mais fácil de descobrir qual o problema. Mas pensando aqui, deve ser pq você está usando uma imagem que não é RGBA (uma imagem com transparência). Não deveria ser necessário usar uma imagem RGBA, mas eu esqueci de programar pra imagens RGB também.

Que novo pixelcanvas é esse? Eu entrei no pixelcanvas agora, e vi que existe um novo atributo `h`, mas ele não é a soma de `x` e `y`.

**Comment by zzz1337-sys** [comment]
@possatti h = x + y + 42

**Comment by possatti** [comment]
E vocês sabem pra que serve esse h? Parece meio inútil.

On Jul 13, 2017 18:31, ZeedyPixel <notifications@github.com> wrote:

@possatti<https://github.com/possatti> h = x + y + 42

**Comment by zzz1337-sys** [comment]
Só para dificultar nossa vida.

**Comment by possatti** [comment]
Kkkkkkk

On Jul 13, 2017 21:59, ZeedyPixel <notifications@github.com> wrote:

Só para dificultar nossa vida.

**Comment by zzz1337-sys** [comment]
Achei um bot que decodifica o bigchunk, talvez possa te ajudar

https://github.com/RogerioBlanco/PixelCanvasBot/blob/master/src/pixelcanvasio.py

**Comment by itsfolf** [comment]
@possatti o h mudou, agora ele vem dos cookies do browser, tem um cookie chamado "DUCK" que define o nome da variavel (neste caso, o meu em vez de ser h é o). E é "x + y + 22".

Esse o erro:
```
C:\Users\ricar\Desktop\pixelbot-master>python botfactory.py idk.png 500 400 f1cfb1db31ca3da369bcf7ffdb4723da
Parsing file...
Producing bot from image 'idk.png' with resolution 753x182.
Traceback (most recent call last):
  File "botfactory.py", line 141, in <module>
    main()
  File "botfactory.py", line 115, in main
    points = points_from_image(args.file_path)
  File "botfactory.py", line 73, in points_from_image
    if pixel[3] != 0:
IndexError: tuple index out of range
``` 
EDIT: Tentei adicionar uma linha transparente na imagem e não funcionou.

Já agora, eu tenho um geito de pegar a fingerprint pelo javascript, posso te passar se quiser.

**Comment by zzz1337-sys** [comment]
O fingerprint pode ser gerado, não precisa de um código extenso para fazer, gerar uma string com 32 carácteres, aAbBcCdD...123...

Tentei pensar em algo para te ajudar a rodar o arquivo, porém n consegui.

**Comment by possatti** [comment]
Pessoal, obrigado por todo o suporte até aqui. Quando eu comecei esse projeto eu imaginei que a dificuldade máxima seria o Google reCaptcha, o fingerprint, e o bigchunk. Mas agora está claro que os criadores do pixelcanvas.io estão dispostos a tornar as coisas ainda mais difíceis. Sempre que tiver um bot funcionando, eles vão colocar mais um empecilho, esse `DUCK` é um exemplo disso.

Eu ainda acredito que um bot é 100% possível. Mas eu perdi o ânimo e estou sem tempo para manter esse projeto. Ainda vou deixar o código aqui na esperança de que seja útil pra alguém. Mas não esperem mais atualizações.

Abraços. E mais uma vez, obrigado pela ajuda.

**Comment by possatti** [comment]
O repositório do Rogério ([RogerioBlanco/PixelCanvasBot](https://github.com/RogerioBlanco/PixelCanvasBot)) parece estar em desenvolvimento. Não sei se está funcionando, mas ele parece ter incorporado as mudanças do `DUCK` e tal. Sugiro que vocês deem uma olhada lá.
